version: "2.3"
services:
  local_debug:
    build: ..
    volumes:
      - ./notebooks:/notebooks
      - ../bias_transfer:/notebooks/bias_transfer
      - ../bias_transfer/data:/notebooks/data
      - ../mlutils:/notebooks/mlutils
      - ../nnfabrik:/notebooks/nnfabrik
      - /tmp/djcache:/cache
    env_file: .env
    entrypoint: ""
  local_develop:
    build: .
    volumes:
      - ./notebooks:/notebooks
      - ../bias_transfer:/notebooks/bias_transfer
      - ../bias_transfer/data:/notebooks/data
      - ../mlutils:/notebooks/mlutils
      - ../nnfabrik:/notebooks/nnfabrik
      - /tmp/djcache:/cache
    ports:
      - "8888:8888"
    env_file: .env
  server_develop:
    build: ..
    volumes:
      - ./notebooks:/notebooks
      - ../bias_transfer:/notebooks/bias_transfer
      - ../bias_transfer/data:/notebooks/data
      - ../mlutils:/notebooks/mlutils
      - ../nnfabrik:/notebooks/nnfabrik
      - /tmp/djcache:/cache
    ports:
      - "127.0.0.1:10140:8888"
    env_file: .env
    runtime: nvidia
  server_job:
    build: ..
    volumes:
        - ./notebooks:/notebooks
        - ../bias_transfer:/notebooks/bias_transfer
        - ../bias_transfer/data:/notebooks/data
        - ../mlutils:/notebooks/mlutils
        - ../nnfabrik:/notebooks/nnfabrik
        - /tmp/djcache:/cache
    env_file: .env
    runtime: nvidia
    entrypoint: python3
    working_dir: /notebooks/bias_transfer/bias_transfer
    command: main.py

